#!/bin/bash

SRC_DIR="sources"

declare -a SUBFOLDERS
declare -a OUTPUT

TOTAL_WIDTH=80

SUBFOLDERS=($(find "$SRC_DIR" -mindepth 1 -maxdepth 1 -type d | sort))

OUTPUT+=("# --------------------------------- PATHNAMES -------------------------------- #")
OUTPUT+=("")

for SUBFOLDER in "${SUBFOLDERS[@]}"; do
    FOLDER_NAME=$(basename "$SUBFOLDER")
    UPPERCASE_FOLDER_NAME=$(echo "$FOLDER_NAME" | tr '[:lower:]' '[:upper:]')
    OUTPUT+=("SRC_${UPPERCASE_FOLDER_NAME}\t\t:=\t$FOLDER_NAME/")
done
OUTPUT+=("")

generate_header() {
    local name="$1"
    local name_length="${#name}"
    local side_dashes_count="$(( (TOTAL_WIDTH - name_length - 6) / 2 ))"  # Adjust for spacing and two dashes around the name
    local extra_dash="$(( (TOTAL_WIDTH - name_length - 6) % 2 ))"

    local header="$(printf '%*s' "$((side_dashes_count + extra_dash))" | tr ' ' '-') $name $(printf '%*s' "$side_dashes_count" | tr ' ' '-')"

    echo "$header"
}

PROGRAM_HEADER=$(generate_header "PROGRAM")
OUTPUT+=("# $PROGRAM_HEADER #")
OUTPUT+=("")
OUTPUT+=("SRC\t\t\t\t+=\tmain.c")
OUTPUT+=("")

for SUBFOLDER in "${SUBFOLDERS[@]}"; do
    FOLDER_NAME=$(basename "$SUBFOLDER")
    UPPERCASE_FOLDER_NAME=$(echo "$FOLDER_NAME" | tr '[:lower:]' '[:upper:]')

    # Find all .c files in the subfolder and its subdirectories
    C_FILES=($(find "$SUBFOLDER" -type f -name "*.c" | sort))

    if [ ${#C_FILES[@]} -gt 0 ]; then
        HEADER=$(generate_header "$UPPERCASE_FOLDER_NAME")
        OUTPUT+=("# $HEADER #")
        OUTPUT+=("")
        for C_FILE in "${C_FILES[@]}"; do
            # Get the path relative to the subfolder
            RELATIVE_PATH=${C_FILE#"$SUBFOLDER/"}
            OUTPUT+=("SRC\t\t\t\t+=\t\$(SRC_${UPPERCASE_FOLDER_NAME})$RELATIVE_PATH")
        done
        OUTPUT+=("")
    fi
done

for LINE in "${OUTPUT[@]}"; do
    echo -e "$LINE"
done

